function residual = fmri_correctmovement(data, movementfilepath)
% FMRI_CORRECTMOVEMENT  Removes motion artifacts from fMRI data via regression.
%
% Regresses out motion parameters from the fMRI time series using ordinary
% least squares (OLS). The motion regressors are z-scored before regression
% to ensure numerical stability. The residuals represent the data with motion-
% related variance removed.
%
% Usage:
%   residual = fmri_correctmovement(data, movementfilepath)
%
% Inputs:
%   DATA             - fMRI time series, either:
%                        vectorized (T x 228453) — scans in rows, voxels in cols
%                        volume     (91 x 109 x 91 x T)
%   MOVEMENTFILEPATH - Path to the motion parameter file (string).
%                      The file should contain a numeric matrix of size
%                      (T x P) where P is the number of motion regressors
%                      (typically 6: 3 translations + 3 rotations).
%
% Outputs:
%   RESIDUAL - Motion-corrected data in the same format as DATA input
%              (T x 228453 if vectorized, 91 x 109 x 91 x T if volume).
%
% Examples:
%   residual = fmri_correctmovement(data, 'sub01_motion.txt');
%   residual = fmri_correctmovement(voldata, '/data/motion/sub04.par');
%
% Notes:
%   Motion parameter files are typically generated by SPM (rp_*.txt) or
%   FSL (*.par). Both 6-column (rigid body) and extended regressor sets
%   (e.g., 24-parameter) are accepted.
%
% See also: fmri_detrend, fmri_tempsmooth, fmri_readnii

% --- handle volume input ----------------------------------------------
isvol = false;
if ndims(data) == 4
    isvol    = true;
    volsize  = size(data);
    data     = reshape(data, [], volsize(4))';  % T x voxels
elseif ndims(data) == 3
    error('fmri_correctmovement:badInput', ...
          'DATA must be 4D volume (91x109x91xT) or 2D vectorized (Tx228453).');
end

% --- load and z-score motion regressors -------------------------------
X = zscore(load(movementfilepath));   % T x P
[T, V] = size(data);

% --- OLS regression with intercept ------------------------------------
% Add constant column so residuals retain mean signal
Xc       = [ones(T,1), X];            % T x (P+1)
B        = (Xc' * Xc) \ (Xc' * data); % (P+1) x V
residual = data - Xc * B;             % T x V  (motion component removed)

% --- restore volume format if input was 4D ----------------------------
if isvol
    residual = reshape(residual', volsize(1), volsize(2), volsize(3), volsize(4));
end
